version: '3.8'

services:
  db:
    image: postgres:16.1-alpine
    restart: always
   # volumes:
    #  - ./src/migration/migration.sql:/docker-entrypoint-initdb.d/migration.sql
    environment:
      POSTGRES_PASSWORD: mat87
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    container_name: myapp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=4667
    ports:
      - 4667:4667
    depends_on:
      db:
        condition: service_healthy
